Repository SE25GroupProject/my-cookbook, pull requests merged in 2025-02, with the labels that each got.

#27 Frontend testing
  .github/workflows/build.yml
  .gitignore
  docker-compose.yml
  dockerout.txt
  frontend/.dockerignore
  frontend/.eslintrc.json
  frontend/Dockerfile
  frontend/babel.config.js
  frontend/jest.config.js
  frontend/package.json
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/features/AppContent/HomePage/HomePage.test.tsx
  frontend/src/features/AppContent/HomePage/MealPage.test.tsx
  frontend/src/features/AppContent/RecipeInformation/RecipeInformation.deprecated.test.tsx
  frontend/src/features/AppContent/RecipeInformation/RecipeInformation.test.tsx
  frontend/src/features/AppContent/RecipeInformation/RecipeInformation.tsx
  frontend/src/features/Header/Header.test.tsx
  frontend/src/features/Navbar/Navbar.test.tsx
  frontend/src/features/ShoppingList/SmartShoppingList.test.tsx
  frontend/src/reportWebVitals.ts
  frontend/src/store.ts
  frontend/tsconfig.json
  frontend/yarn.lock
  package-lock.json
Labels: bug, enhancement

#32 Fixed the python file so it wouldn't fail on startup
  api/Dockerfile
  api/db/database.py
Labels: bug

#35 Posts
  api/db/createPostReactionsTable.sql
  api/db/createPostTable.sql
  api/db/database.py
  api/db/objects.py
  api/main.py
  api/routes.py
  tests/test_posts_api.py
Labels: enhancement

#43 Added and tested comments
  api/db/createCommentsTable.sql
  api/db/database.py
  api/db/objects.py
  api/routes.py
  tests/test_comments_api.py
Labels: enhancement, testing

#39 User favorite recipes
  api/db/createRecipeTable.sql
  api/db/createUserRecipeTable.sql
  api/db/createUserTable.sql
  api/db/database.py
  api/db/objects.py
  api/routes.py
Labels: enhancement

#44 Frontend testing
  .github/workflows/python-test.yml
  .gitignore
  api/Dockerfile
  api/db/convertJsonToSql.py
  api/db/createMainDb.py
  api/db/createMealPrepTable.sql
  api/db/database.py
  api/db/objects.py
  api/dbMiddleware.py
  api/main.py
  api/models.py
  api/routes.py
  api/tests/__init__.py
  api/tests/test_api.py
  api/tests/test_shopping_list.py
  docker-compose.yml
  frontend/package.json
  frontend/src/features/AppContent/Authentication/Profile.test.tsx
  frontend/src/features/AppContent/Authentication/Profile.tsx
  frontend/src/features/AppContent/MealPlan/MealPage.tsx
  frontend/src/features/AppContent/MealPlan/MealPlanSlice.tsx
  frontend/src/features/AppContent/NutritionFilter/CustomizedAccordions.tsx
  frontend/src/features/AppContent/RecipeInformation/RecipeInformation.tsx
  frontend/src/features/AppContent/RecipeList/RecipeLIstItem.tsx
  frontend/src/features/AppContent/RecipeList/RecipeList.tsx
  frontend/src/features/AppContent/RecipeList/RecipeListSlice.ts
  frontend/src/features/AppContent/ShoppingList/ShoppingListSlice.tsx
  frontend/src/features/AppContent/ShoppingList/SmartShoppingList.tsx
  frontend/src/features/AppContent/SocialMedia/CommentItem.tsx
  frontend/src/features/AppContent/SocialMedia/PostItem.tsx
  frontend/src/features/AppContent/SocialMedia/PostModal.tsx
  frontend/src/features/AppContent/SocialMedia/SocialMedia.test.tsx
  frontend/src/features/AppContent/SocialMedia/SocialMedia.tsx
  frontend/src/features/AppContent/SocialMedia/SocialSlice.tsx
  frontend/src/features/AppContent/UserRecipes/RecipeForm.tsx
  frontend/src/features/AppContent/testVariables.tsx
  frontend/src/features/api/apiSlice.ts
  frontend/src/features/api/types.ts
  frontend/yarn.lock
  tests/test_api.py
Labels: bug, enhancement

#40 Refactor old recipe routes
  api/routes.py
  tests/.env
Labels: bug, testing

#47 Mdsanche fixing tests
  CITATION.cff
  CONTRIBUTING.md
  README.md
  api/Dockerfile
  api/__pycache__/__init__.cpython-311.pyc
  api/__pycache__/main.cpython-312.pyc
  api/__pycache__/models.cpython-312.pyc
  api/__pycache__/routes.cpython-312.pyc
  api/db/database.py
  api/routes.py
  api/tests/test_api.py
  api/tests/test_comments_api.py
  api/tests/test_posts_api.py
  api/tests/test_shopping_list.py
  assets/custom-recipes.png
  assets/favorite-recipes.png
  assets/social-forum.png
  assets/user-accounts.png
Labels: testing

#49 Frontend testing
  api/db/database.py
  api/models.py
  api/routes.py
  frontend/.babelrc
  frontend/MealPlan.pdf
  frontend/babel.config.js
  frontend/jest.config.dep.js
  frontend/jest.config.js
  frontend/jest.environment.js
  frontend/package.json
  frontend/src/features/AppContent/Authentication/Profile.test.tsx
  frontend/src/features/AppContent/Authentication/Profile.tsx
  frontend/src/features/AppContent/MealPlan/MealPage.test.tsx
  frontend/src/features/AppContent/MealPlan/MealPage.tsx
  frontend/src/features/AppContent/RecipeInformation/RecipeInformation.tsx
  frontend/src/features/AppContent/RecipeList/RecipeLIstItem.tsx
  frontend/src/features/AppContent/ShoppingList/SmartShoppingList.test.tsx
  frontend/src/features/AppContent/SocialMedia/PostModal.tsx
  frontend/src/features/AppContent/SocialMedia/SocialMedia.test.tsx
  frontend/src/features/AppContent/SocialMedia/SocialMedia.tsx
  frontend/src/features/AppContent/SocialMedia/SocialSlice.tsx
  frontend/src/features/AppContent/UserRecipes/RecipeForm.tsx
  frontend/src/features/AppContent/UserRecipes/UserRecipeSlice.ts
  frontend/src/features/api/apiSlice.ts
  frontend/src/features/api/msw.ts
  frontend/src/features/api/types.ts
  frontend/src/fileMock.js
  frontend/src/setupTests.ts
  frontend/src/styleMock.js
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: enhancement
